import transfersRoutes from "./transfers/transfers.routes.js";
import departmentOrdersRoutes from "./department-orders/department-orders.routes.js";
import ordersRoutes from "./orders/orders.routes.js";
import { Router } from "express";
import { requireAuth } from "../../shared/middleware/auth.middleware.js";
import categoriesRoutes from "./categories/categories.routes.js";
import brandsRoutes from "./brands/brands.routes.js";
import warehousesRoutes from "./warehouses/warehouses.routes.js";
import productsRoutes from "./products/products.routes.js";
import stockRoutes from "./stock/stock.routes.js";
import movementsRoutes from "./movements/movements.routes.js";
import purchasesRoutes from "./purchases/purchases.routes.js";
const router = Router();
router.use(requireAuth);
router.use(categoriesRoutes);
router.use(brandsRoutes);
router.use(warehousesRoutes);
router.use(productsRoutes);
router.use(stockRoutes);
router.use(movementsRoutes);
router.use(purchasesRoutes);
router.use(ordersRoutes);
router.use(departmentOrdersRoutes);
router.use(transfersRoutes);
export default router;
