import { Router } from "express";
import { requireAuth } from "../../shared/middleware/auth.middleware.js";
import positions from "./positions/positions.routes.js";
import employees from "./employees/employees.routes.js";
import contracts from "./contracts/contracts.routes.js";
import salaries from "./salaries/salaries.routes.js";
import attendance from "./attendance/attendance.routes.js";
import payrolls from "./payrolls/payrolls.routes.js";
const router = Router();
router.use(requireAuth);
router.use("/positions", positions);
router.use("/records/contracts", contracts);
router.use("/records/salaries", salaries);
router.use("/records/attendance", attendance);
router.use("/records/payrolls", payrolls);
router.use("/", employees);
export default router;
