/** Nadir Health Organization color tokens. CSS equivalents live in index.css. */
export const brandColors = {
  blue: "#07599A",
  blueDark: "#06487D",
  blueLight: "#E8F3FB",
  teal: "#20B4B8",
  tealDark: "#168C90",
  tealLight: "#E5F8F8",
} as const;

export const colors = {
  brand: brandColors,
  light: {
    primary: brandColors.blue,
    primaryHover: "#064E87",
    primaryPressed: "#043D6B",
    primarySubtle: brandColors.blueLight,
    onPrimary: "#FFFFFF",
    secondary: brandColors.teal,
    secondaryHover: "#199DA1",
    secondaryPressed: brandColors.tealDark,
    secondarySubtle: brandColors.tealLight,
    onSecondary: "#062F31",
    background: "#F6F9FC",
    surface: "#FFFFFF",
    surfaceRaised: "#FFFFFF",
    surfaceMuted: "#EEF4F7",
    text: {
      primary: "#102A43",
      secondary: "#52677A",
      muted: "#718396",
      inverse: "#FFFFFF",
      link: brandColors.blue,
    },
    border: "#D9E3EA",
    borderStrong: "#B8C7D1",
    focus: brandColors.teal,
    success: "#15803D",
    warning: "#B45309",
    error: "#DC2626",
    info: "#0284C7",
  },
  dark: {
    primary: "#58A9E3",
    primaryHover: "#75B9E8",
    primaryPressed: "#91C8ED",
    primarySubtle: "#123B5A",
    onPrimary: "#041E31",
    secondary: "#4FD0D2",
    secondaryHover: "#70DADB",
    secondaryPressed: "#91E3E4",
    secondarySubtle: "#103F42",
    onSecondary: "#052D2F",
    background: "#07151F",
    surface: "#0D202D",
    surfaceRaised: "#122A39",
    surfaceMuted: "#183342",
    text: {
      primary: "#F0F7FA",
      secondary: "#B8CAD4",
      muted: "#8EA5B2",
      inverse: "#07151F",
      link: "#75C7F2",
    },
    border: "#294454",
    borderStrong: "#3D5B6B",
    focus: "#4FD0D2",
    success: "#4ADE80",
    warning: "#FBBF24",
    error: "#FB7185",
    info: "#38BDF8",
  },
} as const;

export type ThemeMode = "light" | "dark";
export type ThemeColors = (typeof colors)[ThemeMode];
